# Homework 01 Till Meineke

## Q1. Pandas version

In [98]:
import pandas as pd

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [99]:
pd_version = pd.__version__

print("My version of pandas is: ", pd_version)

My version of pandas is:  2.2.2


## Getting the data

For this homework, we'll use the Laptops Price dataset. Download it from
[here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv).

You can do it with wget:

```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
```

Read it with Pandas.

In [100]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

!wget $url -O ./data/laptops.csv

data = "./data/laptops.csv"

df = pd.read_csv(data)
df.head(2)

--2024-09-21 09:39:33--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)… 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8001::154, ...
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 298573 (292K) [text/plain]
Wird in »./data/laptops.csv« gespeichert.

./data/laptops.csv  100%[===================>] 291,58K  --.-KB/s    in 0,07s   

2024-09-21 09:39:33 (4,10 MB/s) - »./data/laptops.csv« gespeichert [298573/298573]



Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0

## Q2. Records count

How many records are in the dataset?

In [101]:
print("The number of records in the dataset is: ", df.shape[0])

The number of records in the dataset is:  2160


## Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [102]:
print("The number of unique brands in the dataset is: ", df["Brand"].nunique())

The number of unique brands in the dataset is:  27


## Q4. Missing values

How many columns in the dataset have missing values?

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [104]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [105]:
print(f"Columns with missing values: {df.columns[df.isnull().any()].tolist()}")

Columns with missing values: ['Storage type', 'GPU', 'Screen']


In [106]:
print("The number of columns with missing values is: ", df.isnull().sum().nunique() - 1)

The number of columns with missing values is:  3


## Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [107]:
print(
    "The maximum final price of Dell notebooks in the dataset is: $",
    df[df["Brand"] == "Dell"]["Final Price"].max(),
)

The maximum final price of Dell notebooks in the dataset is: $ 3936.0


## Q6. Median value of Screen

In [108]:
# df["Screen"].value_counts()

1. Find the median value of `Screen` column in the dataset.

In [109]:
median_screen = df["Screen"].median()
print("Median value of `screen` column is: ", median_screen)

Median value of `screen` column is:  15.6


2. Next, calculate the most frequent value of the same Screen column.

In [110]:
print(
    "The most frequent value of the same Screen column is: ",
    df["Screen"].mode()[0],
)

The most frequent value of the same Screen column is:  15.6


3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.

In [111]:
print(
    "Number of missing values in the `Screen` column is: ",
    df["Screen"].isnull().sum()
)

Number of missing values in the `Screen` column is:  4


In [112]:
df.fillna({"Screen": median_screen}, inplace=True)

In [113]:
print(
    "Number of missing values in the `Screen` column is: ", df["Screen"].isnull().sum()
)

Number of missing values in the `Screen` column is:  0


4. Now, calculate the median value of Screen once again.

In [114]:
print("Median value of `screen` column is: ", df["Screen"].median())

Median value of `screen` column is:  15.6


Has it changed?

- No, it has not changed.

## Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.

In [115]:
df_innjoo = df[df["Brand"] == "Innjoo"]
df_innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

2. Select only columns `RAM`, `Storage`, `Screen`.

In [116]:
columns = ["RAM", "Storage", "Screen"]
df_innjoo_small = df_innjoo[columns]

3. Get the underlying NumPy array. Let's call it `X`.

In [117]:
import numpy as np

X = df_innjoo_small.values
X = np.array(X)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [118]:
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5. Compute the inverse of XTX.

In [119]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

6. Create an array y with values `[1100, 1300, 800, 900, 1000, 1100]`.

In [120]:
y = [1100, 1300, 800, 900, 100, 1100]
y = np.array(y)
y

array([1100, 1300,  800,  900,  100, 1100])

7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [121]:
w = XTX_inv.dot(X.T).dot(y)
w

array([-1.61561057,  1.11532207, 46.67319439])

8. What's the sum of all the elements of the result?

In [122]:
print("The sum of all the elements of the result is: ", w.sum().round(2))

The sum of all the elements of the result is:  46.17


## Homework URL

[Homework](https://github.com/TillMeineke/ML_Zoomcamp2024_hw/blob/main/01-intro/homework_01_till_meineke.ipynb)

## Learning in public links (optional) 

- Setting up [Portfolio homepage](https://medium.com/@till.meineke/how-to-setup-a-portfolio-page-on-github-io-3b951fc94f22)
- Setting up [environments](https://medium.com/@till.meineke/setting-up-the-environments-for-ml-zoomcamp-2024-eceb6e42e36e) on medium
- Setting up [environments](https://www.linkedin.com/posts/tillmeineke_setting-up-the-environments-for-ml-zoomcamp-activity-7244840475675807745-ExVD?utm_source=share&utm_medium=member_desktop) on LinkedIn
- [Learning of the week]((https://www.linkedin.com/pulse/learning-ml-zoomcamp-week-1-introduction-till-meineke-k05mc))
<!-- - []()
- []()
- []() -->

## Time spent on lectures (hours) (optional)

## Time spent on homework (hours) (optional)

## FAQ contribution (FAQ document, optional)